name: CVA CI/CD
on:
  push:
    branches:
      - 'cva'

  pull_request:
    branches:
      - 'cva'

env:
  CI: false

jobs:
  deploy:
    name: build docker image and push to docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push
        id: build-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: esatya/rahat-otp-server:cva
